name: "JSON check"

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
